/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    DateCard: typeof import('./src/components/DateCard.vue')['default']
    DayActivities: typeof import('./src/components/DayActivities.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MonthlyCalendar: typeof import('./src/components/MonthlyCalendar.vue')['default']
    MorningCard: typeof import('./src/components/MorningCard.vue')['default']
    Progress: typeof import('./src/components/Progress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WeeklyCalendar: typeof import('./src/components/WeeklyCalendar.vue')['default']
  }
}
